version: '3.1'

services:

  database:
    image: postgres
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: car_rental
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080